use std::error::Error;

fn main() {}
